const data = [
    {
        id: '1',
        name: 'Тренч из габардина со вставкой в клетку',
        count: '2',
        year: '2021',
        manufacturer: 'Burberry',
        price: '110 000',
        priceNum: 110000,
        size: 's',
        color: 'beige',
        gender: 'female',
        popular: false,

    },
    {
        id: '2',
        name: 'Укороченный тренч Wimbledon',
        count: '3',
        year: '2022',
        manufacturer: 'Burberry',
        price: '123 000',
        priceNum: 123000,
        size: 'm',
        color: 'black',
        gender: 'male',
        popular: false,

    },
    {
        id: '3',
        name: 'Экспедиционная парка',
        count: '5',
        year: '2021',
        manufacturer: 'Canada Goose',
        price: '116 000',
        priceNum: 116000,
        size: 's',
        color: 'white',
        gender: 'female',
        popular: true,

    },
    {
        id: '4',
        name: 'Женская непромокаемая куртка Salida',
        count: '4',
        year: '2021',
        manufacturer: 'Canada Goose',
        price: '46 000',
        priceNum: 46000,
        size: 'xs',
        color: 'pink',
        gender: 'female',
        popular: false,

    },
    {
        id: '5',
        name: 'Борден Бомбер Блэк Лейбл',
        count: '2',
        year: '2022',
        manufacturer: 'Canada Goose',
        price: '83 000',
        priceNum: 83000,
        size: 'l',
        color: 'grey',
        gender: 'male',
        popular: false,

    },
    {
        id: '6',
        name: 'Водоотталкивающая парка',
        count: '4',
        year: '2021',
        manufacturer: 'H&M',
        price: '4 000',
        priceNum: 4000,
        size: 's',
        color: 'black',
        gender: 'female',
        popular: true,

    },
    {
        id: '7',
        name: 'Парка свободного кроя',
        count: '3',
        year: '2022',
        manufacturer: 'H&M',
        price: '4 700',
        priceNum: 4700,
        size: 'm',
        color: 'beige',
        gender: 'female',
        popular: false,

    },
    {
        id: '8',
        name: 'Куртка бомбер',
        count: '3',
        year: '2022',
        manufacturer: 'H&M',
        price: '3 000',
        priceNum: 3000,
        size: 'm',
        color: 'beige',
        gender: 'male',
        popular: true,

    },
    {
        id: '9',
        name: 'Водоотталкивающая куртка',
        count: '3',
        year: '2021',
        manufacturer: 'H&M',
        price: '6 000',
        priceNum: 6000,
        size: 'l',
        color: 'beige',
        gender: 'male',
        popular: false,

    },
    {
        id: '10',
        name: 'Двустороннее пальто-трансформатор',
        count: '2',
        year: '2022',
        manufacturer: 'Karl',
        price: '42 300',
        priceNum: 42300,
        size: 's',
        color: 'pink',
        gender: 'female',
        popular: false,

    },
    {
        id: '11',
        name: 'Ультрасветоотражающая парка',
        count: '3',
        year: '2021',
        manufacturer: 'Karl',
        price: '35 000',
        priceNum: 35000,
        size: 'm',
        color: 'grey',
        gender: 'female',
        popular: false,

    },
    {
        id: '12',
        name: 'Утепленная парка',
        count: '2',
        year: '2021',
        manufacturer: 'Karl',
        price: '37 000',
        priceNum: 37000,
        size: 'l',
        color: 'black',
        gender: 'male',
        popular: false,

    },
    {
        id: '13',
        name: 'Ветровка ADICOLOR',
        count: '4',
        year: '2022',
        manufacturer: 'Adidas',
        price: '7 600',
        priceNum: 7600,
        size: 's',
        color: 'black',
        gender: 'female',
        popular: true,

    },
    {
        id: '14',
        name: 'Зимняя куртка BSC с 3 полосками',
        count: '4',
        year: '2022',
        manufacturer: 'Adidas',
        price: '7 600',
        priceNum: 7600,
        size: 'm',
        color: 'pink',
        gender: 'female',
        popular: false,

    },
    {
        id: '15',
        name: 'Парка TRAVEER',
        count: '2',
        year: '2022',
        manufacturer: 'Adidas',
        price: '12 000',
        priceNum: 12000,
        size: 'm',
        color: 'black',
        gender: 'male',
        popular: true,

    }

]

export default data